import Head from "next/head";
import styles from "../styles/Home.module.scss";
import io from "socket.io-client";
import Chat from "../components/Chat";
import { useState, useEffect, useRef } from "react";

let socket = null;

export default function Home() {
  const [messages, setMessages] = useState([]);
  const [inputData, setInputData] = useState("");
  const textBoxRef = useRef(null);
  const messagesEnd = useRef(null);

  useEffect(() => socketHandler(), []);

  useEffect(() => scrollToEnd(), [messages]);

  useEffect(() => adjustTextBox(), [inputData]);

  async function socketHandler() {
    await fetch("/api/socket");
    socket = io();

    socket.on("connect", () => {
      console.log("connected");
    });

    socket.on("message-receive", (message) => {
      insertChat(message);
    });
  }

  function inputChangeHandler(event) {
    // adjustTextBox();
    setInputData(event.target.value);
  }

  function handleSubmit(event) {
    event.preventDefault();
    // console.log(inputData);
    if (inputData) {
      socket.emit("message", inputData);
      insertChat({ sender: "user", message: inputData });
      setInputData("");
    }
  }

  function insertChat(message) {
    setMessages((prevList) => [...prevList, message]);
  }

  function adjustTextBox() {
    textBoxRef.current.style.height = "";
    textBoxRef.current.style.height = `${Math.min(
      textBoxRef.current.scrollHeight,
      128
    )}px`;
  }

  function scrollToEnd() {
    messagesEnd.current.scrollIntoView({ behavior: "smooth" });
  }

  const messageElements = messages.map((msg, index) => (
    <Chat key={index} sender={msg.sender} message={msg.message} />
  ));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul className={styles["chat-list"]}>
          <li className={styles.welcome}>
            <h1
              className={`${styles["text-center"]} ${styles["margin-bottom"]}`}
            >
              Welcome to NextChat!
            </h1>
            <p className={styles["text-center"]}>
              Send your first message to everyone by typing at the textbox.
            </p>
          </li>
          {messageElements}
          <li ref={messagesEnd}></li>
        </ul>
        <form className={styles.form} onSubmit={handleSubmit}>
          <textarea
            className={styles.textbox}
            ref={textBoxRef}
            // contentEditable="true"
            onChange={inputChangeHandler}
            value={inputData}
            // suppressContentEditableWarning="true"
            // role="textbox"
            rows="1"
            placeholder="Type message here..."
          ></textarea>
          <button type="submit" className={styles.button}>
            Send
          </button>
        </form>
      </main>
    </div>
  );
}
